### ISSUE TITLE
StartExplorer Maintainer Wanted discussion & this should be part of Eclipse

### ISSUE THREAD

**Issue by paulvi** [fabioz/startexplorer#64]
This is ticket for discussion.

Frankly I don't think there would be someone to continue. Based on my experience with https://github.com/Nodeclipse/coffeescript-eclipse

The weird thing is that I think there were 1 or 2 similar project starting just within a year, and of course with different names. It looks like new authors did not even tried to search before making  new Start/Open/Launch-Explorer/Shell/Cmd/

I have an idea to add all those name names into marketplace entry.
Would you please agree to transfer marketplace entry http://marketplace.eclipse.org/content/startexplorer to me or make me maintainer (for marketplace entry only)

Any way I think it is worth trying adding "Maintainer Wanted" on marketplace entry as well.

And one more thing. Why not just contribute it to Eclipse IDE. That would be enormous final release, but StartExplorer is the one that should be standard feature within Eclipse.

**Comment by paulvi** [comment]
Take a look at [Bug 473539 - [TERMINALS] plus StartExplorer = ?](https://bugs.eclipse.org/bugs/show_bug.cgi?id=473539)

TM Terminals is nice project with Martin Oberhuber always giving response and advise, not to mention great Terminal within Eclipse.

**Comment by sleicht** [comment]
I like this project and would be very happy to see it contributed to eclipse. Unfortunately I don't see myself as new maintainer.

**Comment by basti1302** [comment]
Adding it to Eclipse so that is a part of an Eclipse distro out of the box in one form or the other would be awesome. I'd totally support this (including necessary changes to enable the transition).

@sleicht maybe you could give vote for it here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=473539

**Comment by paulvi** [comment]
@sleicht @basti1302 It looks like we need to find proper home for the project. Maybe Eclipse Workbench? 

[Bug 477259 - Please help find Eclipse project that would help onboard StartExplore project](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477259)

Maybe @vogella could point in right direction.

**Comment by paulvi** [comment]
Also there are some Eclipse guru who are active on GitHub

@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @PaulVI @fbricon @piotrtomiak @jabby

And well, why this can't be Eclipse project on its own, and be hosted on GitHub?

Like https://github.com/eclipse/thym, https://github.com/eclipse/vertx, https://github.com/eclipse/smarthome, https://github.com/eclipse/buildship

**Comment by basti1302** [comment]
@paulvi thanks for chiming in. Unfortunately I am pretty clueless about how the various Eclipse projects are structured/organized and how to get this into Eclipse... your help is really appreciated.

**Comment by paulvi** [comment]
From https://eclipse.org/projects/ then https://wiki.eclipse.org/Development_Resources/HOWTO/Starting_A_New_Project then long questionnaire at https://projects.eclipse.org/node/add/project-proposal

I don't really think that StartExplorer can be Eclipse project on its own (as each Eclipse project should have its own governance, i.e. several people participating), but the asking would definitely bring to the right home.

**Comment by vogella** [comment]
If you want contribute code to an existing project, please create Gerrit reviews for it. As there is already a terminal implementation in Eclipse this might be the right place to contribute to. Otherwise it is IMHO perfectly fine to continue to develop a plug-in on Github. 

If you are trying to solve the problem that the project is not maintained anymore, the solution is IMHO not to try to contribute it to Eclipse but to find an interested person to maintain it.

**Comment by basti1302** [comment]
@vogella Thanks for your input. Makes sense.

**Comment by maxandersen** [comment]
I haven't looked at startexplorer for a long time but it is worth noting the following:

* since Eclipse Kepler (?) there have been  a Show In > System Explorer on all resources available in most perspectives.

* Ctrl+C/Cmd+C for a file already copies the system path for a file (not sure how long that been the case)

* Open With > Default Editor already exist.

Leaving only "open file in shell" and the various "right click on selected text" actions as unique for startexplorer, afaics ? 

Might be worth noting that to whoever wish to continue it.

**Comment by paulvi** [comment]
I guess Andrey Loskutov @iloveeclipse was one of implementing `Show In > System Explorer` https://github.com/eclipse/eclipse.platform.ui/commit/3cb4156d96595c957cceb9c58918a84be35cb8b9

**Comment by vogella** [comment]
@paulvi You can view the bug behind Andreys commit (or look at the code) and see that this feature existed before. Git history is your friend to see the history of a class

**Comment by paulvi** [comment]
@vogella  https://github.com/basti1302/startexplorer/issues/64#issuecomment-140014251

> If you want contribute code to an existing project, please create Gerrit reviews for it. 

That is like "spend several hours, but there is no guarantee that someone would need it there"

> As there is already a terminal implementation in Eclipse this might be the right place to contribute to. 

That is already [Bug 473539 - [TERMINALS] plus StartExplorer = ?](https://bugs.eclipse.org/bugs/show_bug.cgi?id=473539)

There are some use cases (like long running processes), where built-in terminal does not fit yet.  
Plus with both installed e.g. in [Enide 2015 package](http://www.nodeclipse.org/enide/2015/) user has choice what suits him/her better for the case.

> Otherwise it is IMHO perfectly fine to continue to develop a plug-in on Github.

This should be part of Eclipse, see opening comment. 

> If you are trying to solve the problem that the project is not maintained anymore, the solution is IMHO not to try to contribute it to Eclipse but to find an interested person to maintain it.

This is trick to actually find an interested person to maintain it. :-)

But seriously @basti1302 Bastian has done great work so far, and has no reason to keep it going.  
He'd like to spend time and contribute it to Eclipse, the problem is that Eclipse is helping to find suitable place as in [Bug 477259 - Please help find Eclipse project that would help onboard StartExplore project](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477259)

**Comment by paulvi** [comment]
@maxandersen https://github.com/basti1302/startexplorer/issues/64#issuecomment-140055510

> since Eclipse Kepler (?) there have been a Show In > System Explorer 

And it still can't be open with one keyboard shortcut, vs <kbd>Cltr+Alt+E<kbd> here

1-2 seconds per every use.

> Ctrl+C/Cmd+C for a file already copies the system path for a file

only short file/folder name (). There is also `Copy qualified name` without shortcut, but the path is relative to workspace

> Open With > Default Editor already exist.

Open with (System Editor) has history, and will remember that and will use System Editor next time vs <kbd>Cltr+Alt+A<kbd> for whatever editor was used before.

1-2 seconds per every use.

well, should Eclipse be caring to save seconds for every of its user?

Possibly this project should be next to external tools. 

![image](https://cloud.githubusercontent.com/assets/1614482/9855166/317d0a52-5b3f-11e5-80f7-bc72d2df1f57.png)

They are not have clicked file concept.

**Comment by paulvi** [comment]
Referencing those in https://github.com/eclipse/eclipse.platform.ui/commits/3cb4156d96595c957cceb9c58918a84be35cb8b9/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/handlers/ShowInSystemExplorerHandler.java

@SimonScholz @paulweb515 @mkeller

Please point in right direction to find home.

**Comment by maxandersen** [comment]
@paulvi  you seem to be asking the wrong question. Instead of asking about where to put the system explorer project, then open the above as bugs in the platform to get fixed and try find someone to get it fixed/improved.

If you want system explorer to continue as is and just be as it is now then it is a project on its own - not something to force push into Platform UI as a big block.

**Comment by maxandersen** [comment]
> @maxandersen #64 (comment)
> 
>     since Eclipse Kepler (?) there have been a Show In > System Explorer
> 
> And it still can't be open with one keyboard shortcut, vs Cltr+Alt+E here

I just tried and I could assign Ctrl+Alt+E in shortcuts preferences just fine.
If you want a default keyboard shortcut open a bug for that.

btw. I stopped using keyboard shortcuts for specific stuff like this since I can just use Cmd+3 "system" to do it from anywhere.
 
>     Ctrl+C/Cmd+C for a file already copies the system path for a file
> 
> only short file/folder name (). There is also Copy qualified name without shortcut, but the path is relative to workspace

That is not what I see. I select a resource, press Ctrl+C and I have a full path of the file.

And yes, I can assign Copy qualified name to a shortcut too.

The only thing I see missing is the copy single name, but that does not seem to be a crucial thing IMO. 

But open a bug for that one thing missing.
 
>     Open With > Default Editor already exist.
> 
> Open with (System Editor) has history, and will remember that and will use System Editor next time vs Cltr+Alt+A for whatever editor was used before.

Okey, I don't personal see much use for it but again, sounds like something that should be fixed at the platform level rather than adding yet another duplicated mechanism.

> well, should Eclipse be caring to save seconds for every of its user?

of course - and it does.
 
> Possibly this project should be next to external tools.

I don't see how - maybe the very specific sub-feature of launching a shell could fit here.

> image
> 
> They are not have clicked file concept.

there are http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fdebug_launch_uishortcuts.htm which can generate launch proposals based on current selection which could be used to generate launches running the appropriate shell/terminal as a launch.

So again, for me this does not look like "where should systemexplorer be hosted at eclpse" more a "how can the features in system explorer get integrated with the platform".

And i'm happy to help figuring that out but I can't help implement it.

**Comment by jmini** [comment]
> So again, for me this does not look like "where should systemexplorer be hosted at eclpse" more a "how can the features in system explorer get integrated with the platform".
> 
> And i'm happy to help figuring that out but I can't help implement it.

On the long term this is probably the way to go.

In the meantime a lot of users are happy with the features as they are offered, implemented and displayed by the SmartExplorer plugin.

This discussion shows that there is a feature overlapping, but not 100% and not with the same user experience.

The comment from @maxandersen on Bugzilla ([477259#c8](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477259#c8)) makes sense:
> I think trying to bulk move startexplorer into eclipse is not the right path.

---

Could not be eclipselabs on GitHub (see [Bug 462286](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462286)) a new home for this codebase?

With some colleagues, we are trying to figure out what needs to be done:

* Move this project to the eclipselabs organisation and create a team of comiter for that
* Rename the BSN to `org.eclipselabs.smartexplorer`
* Add a Tycho build
* Create a Build Job on Travis CI (Andreas Mülder [has done it for the Yakindu Statechart Tool](http://muelder.blogspot.ch/2015/08/building-eclipse-plugins-with-maven.html) and is happy about it)
* Publish the update site on BinTray (@vogella [has proposed a script for that](http://blog.vogella.com/2014/12/03/publish-an-eclipse-p2-update-site-at-bintray-via-a-shell-script/))

This way we obtain something more sustainable for this plugin.

---

This plan is not incompatible with improving the Eclipse platform (improving it to offer the same functionalities). The long time vision could be that when the features are moved or implemented into the Eclipse platform, the SmartEdit plugin will only be about presentation and user experience (adding the desired shortcuts, adding menus to call the platform actions…). At the end the code base of the SmartExplorer plugin should be reduced.

**Comment by mickaelistria** [comment]
>>> since Eclipse Kepler (?) there have been a Show In > System Explorer

>> And it still can't be open with one keyboard shortcut, vs Cltr+Alt+E here

> I just tried and I could assign Ctrl+Alt+E in shortcuts preferences just fine.
If you want a default keyboard shortcut open a bug for that.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=477451
Trivial fix in progress.

**Comment by paulvi** [comment]
There should have been a few separate issue discussion forked from here, please create

@ all Giving a wider context

Eclipse has got built-in Terminal, launched via <kbd>Cltr+Alt+T</kbd>

[![](http://marketplace.eclipse.org/sites/default/files/styles/ds_solution_screenshot/public/terminals_screenshot.png?itok=Ick3BnGW)](http://marketplace.eclipse.org/content/tm-terminals)

There is also eExplorer (embedded Explorer) #52 I think there exists something for MacOS as welll
![](http://marketplace.eclipse.org/sites/default/files/styles/ds_solution_screenshot/public/eExplorer_breadcrumb.png?itok=weFvCLgD)

Terminal, Terminal and StartExploer are related and should be more integrated.
E.g. using `Show in` <kbd>Alt+Shift+W</kbd>
or `Run External Tool`. External tools are in `Run` menu and in ToolBar, but not in context menu.

![image](https://cloud.githubusercontent.com/assets/1614482/9908063/7f9a35f8-5cc4-11e5-89b6-c63e93ffc6d4.png)


![image](https://cloud.githubusercontent.com/assets/1614482/9908007/2dd0e276-5cc4-11e5-8da4-c8dcee2b72d9.png)

That is why StartExplorer can be part of some bigger future project.   
When there's only one person developing then what Jérémie described is likely smart way.

@jmini https://github.com/basti1302/startexplorer/issues/64#issuecomment-140342665

- [ ] Move this project to the eclipselabs organisation and create a team of comiter for that
- [ ] Rename the BSN to org.eclipselabs.smartexplorer
these two up to those who develop
- [ ] Add a Tycho build
already was here #35 see commits
- [ ] Create a Build Job on Travis CI 
already running for this location, see checkboxes at https://github.com/basti1302/startexplorer/pulls?q=is%3Apr+is%3Aclosed 
- [ ] Publish the update site on BinTray
StartExlploer is small enough, so there is no [benefit in speed, but BinTray gives some nice stats for meditation](http://www.nodeclipse.org/nodeclipse/binaries/bintray/2014/05/09/Nodeclipse-on-Bintray.html)

**Comment by basti1302** [comment]
I wrote some things about the "integrate parts of StartExplorer into the Eclipse UI" at https://bugs.eclipse.org/bugs/show_bug.cgi?id=477259#c12

Summary: Some good ideas, let's see how they work out. As a fallback, if nothing comes out of it, the current status quo is also okay. As said before, I still do bug fixes from time to time and merge PRs. I just will not put a lot of effort into StartExplorer anymore.

Regarding Tycho and Travis build: Yes, Paul added them a while back. Since I was the only person building and publishing this project and they added more hassle than benefit for me, I threw them out eventually but they can easily be resurrected from the git history.

**Comment by vogella** [comment]
I think a good starting point for any contribution is to remove the bits which are already in Eclipse standard.

**Comment by maxandersen** [comment]
@paulvi it is called Run External Tools, not just "Run Tools" and already exist. Just need to have some launch detectors that set it up afaics.

**Comment by paulvi** [comment]
@maxandersen https://github.com/basti1302/startexplorer/issues/64#issuecomment-142033198

yes, "Run External Tools"

![](https://cloud.githubusercontent.com/assets/1614482/9855166/317d0a52-5b3f-11e5-80f7-bc72d2df1f57.png)

**Comment by mickaelistria** [comment]
The shortcut for opening system explorer is now provided by platform UI: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477451

**Comment by fabioz** [comment]
Closing this bug. After seeing the helpwanted on the readme I volunteered with Bastian and he has passed the project over to me -- I must say I only really acknowledged this issue now ;)

My plan is mostly keeping the current status quo of the project (which means I'll keep the project running / integrating fixes and fixing some things myself, although I don't expect to expand on the current focus of the plugin, which does work pretty well on my view -- and I use it daily anyways).

Regarding duplicate functionality from the platform, it's possible that I'll trim some of that in the future and point users to the Eclipse version if it's a better alternative -- although the open explorer itself is probably going to remain there even if only to have a default keybinding and to appear in the StartExplorer menu (this is the may point of this plugin after all)... also, I have nothing against having code copied from here to Eclipse (quite the contrary -- and the license definitely allows it), but I probably won't be doing that work myself.

To finish, there were many different threads on this issue, so, please open new issues if you think they're worth it ;)

**Comment by basti1302** [comment]
I totally forgot to report back here, but full ack on what @fabioz said. I think him taking over is really the ideal outcome. The plans to put parts of this into Eclipse core might have been a nice idea, it just never happened and nobody was pushing it enough.

**Comment by paulvi** [comment]
Huray! Welcome @fabioz Fabio here

**Comment by mickaelistria** [comment]
Thanks @fabioz and @basti1302 .
Using the same shortcut for this operation in Eclipse Platform was a failure: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477451#c10 . We can keep discussing of finding a better one for Eclipse Platform, and you opinion on that would be welcome on the bug.
If there is anything that you believe would be a good candidate for being in Eclipse Platform,just bring the topic on the platform-ui-dev@eclipse.org mailing-list, and we'll be pleased to collaborate with you in order to factorize good pieces of functionality and to deliver more value to more users.
